package ru.syndicate.atmosphere.feature.home.presentation.util

internal fun weatherTitleByWeatherCode(weatherCode: Int) = when(weatherCode) {
    0 -> "Clear sky"
    1 -> "Mainly clear"
    2 -> "Partly cloudy"
    3 -> "Overcast"
    in 45..48 -> "Fog"
    51 -> "Light drizzle"
    53 -> "Moderate drizzle"
    55 -> "Heavy drizzle"
    56 -> "Light freezing drizzle"
    57 -> "Heavy freezing drizzle"
    61 -> "Slight rain"
    63 -> "Moderate rain"
    65 -> "Heavy rain"
    66 -> "Light freezing rain"
    67 -> "Heavy freezing rain"
    71 -> "Slight snow fall"
    73 -> "Moderate snow fall"
    75 -> "Heavy snow fall"
    77 -> "Snow grains"
    80 -> "Slight rain shower"
    81 -> "Moderate rain shower"
    82 -> "Violent rain shower"
    85 -> "Slight snow shower"
    86 -> "Heavy snow shower"
    in 95..99 -> "Thunderstorm"
    else -> ""
}